name: Full_regression_schedule_and_push

on:
  push:
    branches:
      - "master" # Will start the job every time after push into master branch
  schedule:
    - cron: "0 0 * * *" # Automatic start to run the job at the scheduled time at 00:00 UTC


permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Chrome and WebDriver
        run: |
            brew install --cask google-chrome
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Python Syntax Checker
        # You may pin to the exact commit or the version.
        # uses: cclauss/Find-Python-syntax-errors-action@90f67be9fb626b675a3971b1d08ab29851cb721f
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
      - name: Run tests
        run: |
          python -m pytest --verbose --junit-xml=test-results.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/test-results.xml'
          detailed_summary: true
          include_passed: true
